#!/usr/bin/env python3
"""Emit the AXI4-dialect model of Chimera's Cheshire AXI crossbar.

The network is just the module boundary plus one crossbar: every endpoint is a
top-level `!axi4.port`, which the lowering explodes into a payload, a valid and
a ready per channel. Those signals connect straight to the `axi_in_req` /
`axi_out_req` buses in cheshire_soc.sv, because the channel payload structs have
the same layout as PULP's `axi_pkg` channel structs.

Config resolved from cheshire_pkg/chimera_pkg for chimera SelectedCfg=0 with
AXISIM: addr 32, data 32, user 8, 14 slave ports, 7 master ports, 9 address
rules. Master-port ID width is 3 under FEWERAXIBITS (the Verilator perf-model
build) and 6 otherwise.

Usage:
  gen_cheshire_xbar.py          # the AXI4-dialect MLIR model
  gen_cheshire_xbar.py --tb     # the SystemVerilog routing testbench
  gen_cheshire_xbar.py --inst   # the cheshire_soc.sv instantiation
"""

import math
import os
import sys

ADDR, DATA, USER = 32, 32, 8

# Slave ports (masters into the xbar): [0]=dbg, [1]=dma, [2..]=external. The
# external-master count is config-dependent: 12 with the AXISIM preload master
# (the default sim build), 11 without.
NUM_EXT_MST = int(os.environ.get("XBAR_EXT_MST", "12"))
SLV_NAMES = ["dbg", "dma"] + [f"ext_mst{i}" for i in range(NUM_EXT_MST)]

# Master-port ID width. 3 for the Verilator perf-model sim build
# (PERFORMANCE_MODEL+VERILATOR defines FEWERAXIBITS), 6 for VCS and synthesis.
# The slave side is the xbar's widening: mst-id + clog2(#slave ports).
MST_ID = int(os.environ.get("XBAR_MST_ID", "3"))
SLV_ID = MST_ID + math.ceil(math.log2(len(SLV_NAMES)))

# Cheshire asks for MaxTrans 24 on both sides. A port cannot keep more requests
# outstanding than it has IDs, so the slave side gets as close to 24 as its ID
# width allows; the master side takes everything reaching it at once.
OUTSTANDING_SLV = min(24, 1 << MST_ID)
OUTSTANDING_MST = min(1 << SLV_ID, len(SLV_NAMES) * OUTSTANDING_SLV)

# The bursts the crossbar passes through, in AXI4's per-kind beat limits.
BURSTS = "<<fixed, len = 16>, <incr, len = 256>, <wrap, len = 16>>"

# 7 master ports (slaves out): each with its address windows [start, end).
MST = [
    ("dbg",       [(0x01000000, 0x01010000)]),
    ("reg_demux", [(0x22000000, 0x2C000000),    # reg region
                   (0x0E000000, 0x0E010000),    # CLINT
                   (0x2C001000, 0x2C002000)]),  # TopLevelCfgRegs
    ("dma",       [(0x21000000, 0x21001000)]),
    ("dormouse",  [(0x10000000, 0x20000000)]),
    ("memisl",    [(0x08000000, 0x09A00000)]),
    ("cluster0",  [(0x01600000, 0x01800000)]),
    ("cluster1",  [(0x01C00000, 0x01E00000)]),
]

# Port names, in declaration order.
SLV_PORTS = [f"slv{i}_{n}" for i, n in enumerate(SLV_NAMES)]
MST_PORTS = [f"mst{j}_{n}" for j, (n, _) in enumerate(MST)]

# The fifteen signals a port explodes into, and where each one lives in PULP's
# req/resp struct pair: a channel's payload and valid travel with its requester,
# its ready against them.
SIGNALS = [
    ("aw",      "req", "aw"),
    ("awvalid", "req", "aw_valid"),
    ("awready", "rsp", "aw_ready"),
    ("w",       "req", "w"),
    ("wvalid",  "req", "w_valid"),
    ("wready",  "rsp", "w_ready"),
    ("b",       "rsp", "b"),
    ("bvalid",  "rsp", "b_valid"),
    ("bready",  "req", "b_ready"),
    ("ar",      "req", "ar"),
    ("arvalid", "req", "ar_valid"),
    ("arready", "rsp", "ar_ready"),
    ("r",       "rsp", "r"),
    ("rvalid",  "rsp", "r_valid"),
    ("rready",  "req", "r_ready"),
]


def windows(wins):
    return ", ".join(
        f"<base = {b:#x}, last = {e - 1:#x}, burst_specs = {BURSTS}>"
        for b, e in sorted(wins))


def port_type(id_width, wins, outstanding):
    return (f"!axi4.port<addr_width = {ADDR}, data_width = {DATA}, "
            f"write_id_width = {id_width}, read_id_width = {id_width}, "
            f"user_width = {USER}, windows = <{windows(wins)}>, "
            f"outstanding_writes = {outstanding}, "
            f"outstanding_reads = {outstanding}>")


def emit_mlir():
    # A manager can only reach what the crossbar routes, so the slave ports see
    # the union of the master ports' windows - which is also what Cheshire does
    # by tying en_default_mst_port_i to '0.
    reachable = [w for _, wins in MST for w in wins]

    out = ["// Generated by gen_cheshire_xbar.py: Chimera's Cheshire AXI xbar,",
           "// as a module whose boundary ports are the endpoints.",
           f"!mgr = {port_type(MST_ID, reachable, OUTSTANDING_SLV)}"]
    for j, (name, wins) in enumerate(MST):
        out.append(f"!sub{j} = {port_type(SLV_ID, wins, OUTSTANDING_MST)}")
    out.append("")

    ports = ["in %clk_i : !seq.clock", "in %rst_ni : i1"]
    ports += [f"in %{p} : !mgr" for p in SLV_PORTS]
    ports += [f"out {p} : !sub{j}" for j, p in enumerate(MST_PORTS)]
    out.append("hw.module @cheshire_axi_xbar(")
    out.append(",\n".join(f"    {p}" for p in ports) + ") {")

    results = ", ".join(f"%{p}" for p in MST_PORTS)
    mgrs = ", ".join(f"%{p}" for p in SLV_PORTS)
    ins = ", ".join("!mgr" for _ in SLV_PORTS)
    outs = ", ".join(f"!sub{j}" for j in range(len(MST)))
    out.append(f"  {results} = axi4.xbar %clk_i, %rst_ni mgrs {mgrs}")
    out.append(f"    : ({ins}) -> ({outs})")
    out.append(f"  hw.output {results} : {outs}")
    out.append("}")
    return "\n".join(out)


def connections(buses):
    """Name every exploded signal of every port, given per-port req/resp
    expressions as (port, req, rsp) triples."""
    width = max(len(f"{port}_{suffix}")
                for port, _, _ in buses for suffix, _, _ in SIGNALS)
    lines = []
    for port, req, rsp in buses:
        for suffix, struct, field in SIGNALS:
            name = f"{port}_{suffix}"
            expr = (req if struct == "req" else rsp) + "." + field
            lines.append(f"    .{name:<{width}} ({expr})")
    return lines


def instance(name, buses, extra=("    .clk_i,", "    .rst_ni,")):
    lines = [f"  {name} i_axi_xbar ("] + list(extra)
    conns = connections(buses)
    return "\n".join(lines + [c + "," for c in conns[:-1]] + [conns[-1]]
                     + ["  );"])


def emit_tb():
    nslv, nmst = len(SLV_NAMES), len(MST)
    probe = [(name, wins[0][0]) for name, wins in MST]
    DRV = 2  # drive from external-master slave port 2

    buses = [(p, f"in_req[{i}]", f"in_rsp[{i}]")
             for i, p in enumerate(SLV_PORTS)]
    buses += [(p, f"out_req[{j}]", f"out_rsp[{j}]")
              for j, p in enumerate(MST_PORTS)]

    L = []
    a = L.append
    a("// Generated by gen_cheshire_xbar.py --tb. Routing check for the generated")
    a("// Cheshire AXI crossbar: one master issues a single-beat read to an address")
    a("// in each master port's window; the correct master port (and only it) must")
    a("// see the AR with that address. Exercises the real PULP axi_xbar inside the")
    a("// generated wrapper, and the channel struct layouts against axi_pkg's.")
    a('`include "axi/typedef.svh"')
    a("module tb_cheshire_xbar;")
    a("  import axi_pkg::*;")
    a(f"  `AXI_TYPEDEF_ALL_CT(in, in_req_t, in_rsp_t, logic[{ADDR-1}:0], logic[{MST_ID-1}:0], logic[{DATA-1}:0], logic[{DATA//8-1}:0], logic[{USER-1}:0])")
    a(f"  `AXI_TYPEDEF_ALL_CT(out, out_req_t, out_rsp_t, logic[{ADDR-1}:0], logic[{SLV_ID-1}:0], logic[{DATA-1}:0], logic[{DATA//8-1}:0], logic[{USER-1}:0])")
    a("")
    a("  logic clk = 0, rst_n = 0;")
    a("  always #5 clk = ~clk;")
    a("")
    a(f"  in_req_t  in_req  [{nslv}];")
    a(f"  in_rsp_t  in_rsp  [{nslv}];")
    a(f"  out_req_t out_req [{nmst}];")
    a(f"  out_rsp_t out_rsp [{nmst}];")
    a("")
    a(instance("cheshire_axi_xbar", buses,
               extra=["    .clk_i (clk),", "    .rst_ni(rst_n),"]))
    a("")
    a("  // Per-master-port slave: always ready, records whether it saw an AR and")
    a("  // its address, and returns one R beat per read (via an outstanding")
    a("  // counter) so reads complete and don't stall the xbar. `clr` (from the")
    a("  // testbench) resets the seen flags between probes; `seen` has this single")
    a("  // driver.")
    a(f"  logic [{ADDR-1}:0] seen_addr [{nmst}];")
    a(f"  logic             seen [{nmst}];")
    a("  logic clr;")
    a("  for (genvar j = 0; j < %d; j++) begin : g_slv" % nmst)
    a("    logic [7:0] rcnt;")
    a(f"    logic [{SLV_ID-1}:0] rid;")
    a("    wire ar_acc = out_req[j].ar_valid & out_rsp[j].ar_ready;")
    a("    wire r_acc  = out_rsp[j].r_valid  & out_req[j].r_ready;")
    a("    always_comb begin")
    a("      out_rsp[j] = '0;")
    a("      out_rsp[j].ar_ready = 1'b1;")
    a("      out_rsp[j].aw_ready = 1'b1;")
    a("      out_rsp[j].w_ready  = 1'b1;")
    a("      out_rsp[j].r_valid  = (rcnt != 0);")
    a("      out_rsp[j].r.id     = rid;")
    a("      out_rsp[j].r.last   = 1'b1;")
    a("      out_rsp[j].r.resp   = axi_pkg::RESP_OKAY;")
    a("    end")
    a("    always_ff @(posedge clk or negedge rst_n) begin")
    a("      if (!rst_n) begin seen[j] <= 0; seen_addr[j] <= '0; rcnt <= 0; rid <= 0; end")
    a("      else begin")
    a("        if (clr) begin seen[j] <= 0; seen_addr[j] <= '0; end")
    a("        if (ar_acc) begin seen[j] <= 1'b1; seen_addr[j] <= out_req[j].ar.addr; rid <= out_req[j].ar.id; end")
    a("        rcnt <= rcnt + (ar_acc ? 8'd1 : 8'd0) - (r_acc ? 8'd1 : 8'd0);")
    a("      end")
    a("    end")
    a("  end")
    a("")
    a("  // Single-beat read driver on slave port %d; completes the read (r_ready" % DRV)
    a("  // stays high), then the check reads `seen[]`.")
    a(f"  task automatic do_read(input logic [{ADDR-1}:0] addr);")
    a("    @(posedge clk);")
    a(f"    in_req[{DRV}].ar <= '0;")
    a(f"    in_req[{DRV}].ar.addr <= addr;")
    a(f"    in_req[{DRV}].ar.size <= 3'd2;   // 4 bytes")
    a(f"    in_req[{DRV}].ar.burst <= axi_pkg::BURST_INCR;")
    a(f"    in_req[{DRV}].ar_valid <= 1'b1;")
    a(f"    in_req[{DRV}].r_ready <= 1'b1;")
    a("    do @(posedge clk); while (!in_rsp[%d].ar_ready);" % DRV)
    a(f"    in_req[{DRV}].ar_valid <= 1'b0;")
    a("    do @(posedge clk); while (!(in_rsp[%d].r_valid && in_rsp[%d].r.last));" % (DRV, DRV))
    a("  endtask")
    a("")
    a("  int errors = 0;")
    a("  initial begin")
    a(f"    for (int i = 0; i < {nslv}; i++) in_req[i] = '0;")
    a("    clr = 1'b0;")
    a("    repeat (4) @(posedge clk); rst_n = 1; repeat (2) @(posedge clk);")
    a("")
    for j, (name, addr) in enumerate(probe):
        a(f"    // {name}: 0x{addr:08X} should route to master port {j}.")
        a("    clr = 1'b1; @(posedge clk); clr = 1'b0;")
        a(f"    do_read(32'h{addr:08X});")
        a("    repeat (4) @(posedge clk);")
        a(f"    if (!(seen[{j}] && seen_addr[{j}] == 32'h{addr:08X})) begin")
        a(f'      $display("FAIL: {name} 0x{addr:08X} did not reach master port {j}"); errors++;')
        a("    end")
        a(f"    for (int k = 0; k < {nmst}; k++)")
        a(f"      if (k != {j} && seen[k]) begin")
        a(f'        $display("FAIL: {name} 0x{addr:08X} mis-routed to master port %0d", k); errors++;')
        a("      end")
    a("")
    a(f'    if (errors == 0) $display("PASS: all {len(probe)} routes correct");')
    a('    else $display("FAILED: %0d routing error(s)", errors);')
    a("    $finish;")
    a("  end")
    a("")
    a("  initial begin")
    a("    repeat (100000) @(posedge clk);")
    a('    $display("FAIL: timeout"); $finish;')
    a("  end")
    a("endmodule")
    return "\n".join(L)


def slv_bus_index(i):
    # Slave port -> cheshire axi_in_req[] index. [0]=dbg, [1]=dma, [2..]=external.
    if i == 0:
        return "AxiIn.dbg"
    if i == 1:
        return "AxiIn.dma"
    return f"AxiIn.ext_base+{i - 2}"


def mst_bus_index(j):
    # Master port -> cheshire axi_out_req[] index. [0]=dbg, [1]=reg_demux,
    # [2]=dma, [3..]=external.
    return {0: "AxiOut.dbg", 1: "AxiOut.reg_demux", 2: "AxiOut.dma"}.get(
        j, f"AxiOut.ext_base+{j - 3}")


def emit_inst():
    # The cheshire_soc.sv instantiation: a drop-in for `axi_xbar i_axi_xbar`,
    # wired to the axi_in_req/axi_out_req buses by name. Config (Cfg + address
    # map) and test_i are baked into cheshire_axi_xbar.
    buses = [(p, f"axi_in_req[{slv_bus_index(i)}]",
              f"axi_in_rsp[{slv_bus_index(i)}]")
             for i, p in enumerate(SLV_PORTS)]
    buses += [(p, f"axi_out_req[{mst_bus_index(j)}]",
               f"axi_out_rsp[{mst_bus_index(j)}]")
              for j, p in enumerate(MST_PORTS)]
    return instance("cheshire_axi_xbar", buses)


if __name__ == "__main__":
    args = sys.argv[1:]
    if "--tb" in args:
        print(emit_tb())
    elif "--inst" in args:
        print(emit_inst())
    else:
        print(emit_mlir())
