//===----------------------------------------------------------------------===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// This file implements the AXI4 ops.
//
//===----------------------------------------------------------------------===//

#include "circt/Dialect/AXI4/AXI4Ops.h"
#include "circt/Dialect/HW/HWOpInterfaces.h"
#include "mlir/IR/Builders.h"

using namespace circt;
using namespace axi4;
using namespace mlir;

//===----------------------------------------------------------------------===//
// Verifier helpers
//===----------------------------------------------------------------------===//

/// Verify that `module` resolves to an `hw.module`-like symbol.
static LogicalResult verifyModuleSymbol(Operation *op, FlatSymbolRefAttr module,
                                        SymbolTableCollection &symbolTable) {
  Operation *moduleOp = symbolTable.lookupNearestSymbolFrom(op, module);
  if (!moduleOp)
    return op->emitOpError("references unknown symbol @") << module.getValue();
  if (!isa<hw::HWModuleLike>(moduleOp))
    return op->emitOpError("symbol @")
           << module.getValue() << " must refer to an 'hw.module'";
  return success();
}

//===----------------------------------------------------------------------===//
// NodeOp
//===----------------------------------------------------------------------===//

LogicalResult NodeOp::verifySymbolUses(SymbolTableCollection &symbolTable) {
  return verifyModuleSymbol(*this, getModuleAttr(), symbolTable);
}

//===----------------------------------------------------------------------===//
// TableGen generated logic.
//===----------------------------------------------------------------------===//

// Provide the autogenerated implementation guts for the Op classes.
#define GET_OP_CLASSES
#include "circt/Dialect/AXI4/AXI4.cpp.inc"
